a mini theme for blockly
CodeYourFuture/fundamentals-blockly pull request #52
Opened 2022-03-17 17:47 UTC by SallyMcGrath

There's a whole themeing system but the grey block was bugging me so here's a super fast override to theme it in with our variables.

I stacked this PR on my last branch as it's dependent on the previous code

2022-03-17 20:59 UTC, SallyMcGrath commented
Note: I moved the base of this PR to main as the previous dependent PR was merged.

2022-03-17 22:36 UTC, gregdyke requested changes
Wow! (also I found the "toggle night mode" button in my developer tools, so I got to see day mode :D)

Thanks for the flash. Good choice of implementation I think!!

2022-03-17 22:36 UTC, gregdyke commented on style.css
> +  stroke-width: 0;
```suggestion
```
I think showing where the boundary of the box is makes it a bit more crowded, but more obvious that there is a box where things can be placed? Alternatively, play with the transparency>

2022-03-18 08:18 UTC, SallyMcGrath commented
👋 For those following along at home, you can switch your themes in Devtools by pulling up the command palette:

**Shift Command P** 

Then type `emu` to bring up your emulation options. Choose prefers colour scheme light/dark.  / 🧇

2022-03-18 11:23 UTC, gregdyke approved these changes

2022-03-19 00:26 UTC, merged